baseURL = "https://ubuntusecuritypodcast.org/"
languageCode = "en-us"
title = "Ubuntu Security Podcast"
theme = "castanet"
googleAnalytics = "UA-123895434-1"

[params]
site_theme = "orange"
site_layout = "row"
copyright_notice = "Copyright 2018 [Canonical](https://ubuntu.com/)"
description = "A weekly podcast talking about the latest developments and updates from the Ubuntu Security team."
media_prefix = "https://s3-ap-southeast-2.amazonaws.com/ubuntusecuritypodcast/"

[params.feed]
copyright = "Copyright 2018 Canonical"
itunes_author = "Ubuntu Security Team"
itunes_summary = "A weekly podcast talking about the latest developments and updates from the Ubuntu Security team."
itunes_owner_name = "Alex Murray"
itunes_owner_email = "alex.murray@canonical.com"
itunes_image = "https://ubuntusecuritypodcast.org/img/logo_1400.png"
itunes_top_category = "Technology"

[params.social]
twitter = "ubuntu_sec"
twitter_domain = "ubuntu.com"

[params.authors]
[params.authors.Alex]
name = "Alex Murray"
thumbnail = "https://avatars3.githubusercontent.com/u/56540?s=460&v=4"
bio = "Ubuntu Security Tech Lead at Canonical"

[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"
[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "contact"
